---

- name: Install required software packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - dnsmasq
  - git
  - python-pip
  - unzip

- name: Install required Python modules
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
  - git+https://github.com/cablehead/python-consul.git
  - requests

- name: Add vagrant user
  user:
    name: vagrant
    state: present
  become: yes

- name: Add vagrant user public key to authorized_keys file
  authorized_key:
    key: >
      ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    state: present
    user: vagrant
  become: yes
  become_user: vagrant
